#
# This file was auto-generated by civicrm-install.sh, Thu Feb  4 23:24:12 GMT 2016
#
$path = "/var/local/brisskit/drupal/site/civicrm/sites/all/modules/civicrm";

#crm defined constant to config dir -> deals with symlinks
define("CIVICRM_CONFDIR","/var/local/brisskit/drupal/site/civicrm/sites/default");

set_include_path("$path/drupal" . PATH_SEPARATOR . $path . PATH_SEPARATOR . $path."/packages".PATH_SEPARATOR."/var/local/brisskit/drupal/site/civicrm/sites/default");
